version: 2.1
jobs:
  android:
   docker:
      - image: dopaemon/bionic:latest
   steps:
      - run:
          name: Include DPKG i386
          no_output_timeout: 20m
          command: |
            sudo dpkg --add-architecture i386
      - run:
          name: Start Building . . .
          no_output_timeout: 20m
          command: |
             sudo apt-get install openjdk-8-jdk android-tools-adb bc bison build-essential curl flex g++-multilib gcc-multilib gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libesd0-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev -y
workflows:
  version: 2.1
  cooking:
    jobs:
      - android
