version: 2.1
jobs:
  android:
   docker:
      - image: dopaemon/bionic:latest
   steps:
      - run:
          name: Include DPKG i386
          no_output_timeout: 20m
          command: |
            sudo dpkg --add-architecture i386
      - run:
          name: Start Building . . .
          no_output_timeout: 20m
          command: |
             sudo apt-get install openjdk-8-jdk bc bison build-essential curl flex gnupg gperf liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev -y
workflows:
  version: 2.1
  cooking:
    jobs:
      - android
