version: 2.1
jobs:
  MultiROM-Bacon:
   docker:
      - image: dopaemon/docker-image:MultiROM
   steps:
      - run:
          name: Syncing source
          no_output_timeout: 20m
          command: |
            cd ~
            mkdir ~/twrp && cd ~/twrp
            repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-6.0
            repo sync -vf -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - run:
          name: Building
          no_output_timeout: 20m
          command: |
            cd ~/twrp
            git clone -b cm-14.1 https://github.com/LineageOS/android_kernel_oneplus_msm8974.git kernel/oneplus/msm8974
            git clone -b android-6.0.1 https://github.com/KernelPanic-OpenSource/android_device_oneplus_bacon device/oneplus/bacon
            # rm -rf vendor/qcom/opensource/cryptfs_hw
            source build/envsetup.sh
            export ALLOW_MISSING_DEPENDENCIES=true
            export LC_ALL=C
            lunch omni_bacon-eng
            mka -j$(nproc --all) recoveryimage
      - run:
          name: Telegram Upload CI
          no_output_timeout: 20m
          command: |
            cd ~/twrp/out/target/product/bacon
            export ZIPNAME="TWRP-$(date +%d_%m_%Y_%H_%M)-bacon.zip"
            sudo zip -r9 $ZIPNAME . -i *.img
            curl -F chat_id=$CHAT_ID -F document=@$ZIPNAME -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument
workflows:
  version: 2.1
  cooking:
    jobs:
      - MultiROM-Bacon
