version: 2.1
jobs:
  LineageOS-Bacon:
   docker:
      - image: dopaemon/docker-image:android
   steps:
      - run:
          name: Info
          no_output_timeout: 20m
          command: |
            lscpu
            df -h
      - run:
          name: Install Packages
          no_output_timeout: 20m
          command: |
            sudo apt update
            sudo apt full-upgrade -y
            sudo apt install ccache
      - run:
          name: Info
          no_output_timeout: 20m
          command: |
            lscpu
            df -h
      - run:
          name: Syncing Source LineageOS
          no_output_timeout: 20m
          command: |
            cd ~
            mkdir ~/LineageOS && cd ~/LineageOS
            repo init -u https://github.com/LineageOS/android.git -b lineage-18.1
            repo sync -vf -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - run:
          name: Info
          no_output_timeout: 20m
          command: |
            lscpu
            df -h
      - run:
          name: Clone Source Tree For Bacon
          no_output_timeout: 20m
          command: |
            cd ~/LineageOS
            git clone -b lineage-18.1 https://github.com/LineageOS/android_device_oneplus_bacon device/oneplus/bacon
            git clone -b lineage-18.1 https://github.com/LineageOS/android_device_oppo_msm8974-common device/oppo/msm8974-common
            git clone -b lineage-18.1 https://github.com/LineageOS/android_device_oppo_common device/oppo/common
            git clone -b lineage-18.1 https://github.com/LineageOS/android_hardware_sony_timekeep hardware/sony/timekeep
            git clone -b lineage-18.1 https://github.com/LineageOS/android_kernel_oppo_msm8974.git kernel/oppo/msm8974
            git clone -b lineage-18.1 https://github.com/TheMuppets/proprietary_vendor_oppo.git vendor/oppo
            git clone -b lineage-18.1 https://github.com/TheMuppets/proprietary_vendor_oneplus.git vendor/oneplus
      - run:
          name: Info
          no_output_timeout: 20m
          command: |
            lscpu
            df -h
      - run:
          name: Export
          no_output_timeout: 20m
          command: |
            export CCACHE_EXEC=/usr/bin/ccache
            export ALLOW_MISSING_DEPENDENCIES=true
            export LC_ALL=C
      - run:
          name: Building
          no_output_timeout: 20m
          command: |
            cd ~/LineageOS
            source build/envsetup.sh
            lunch lineage_bacon-userdebug
            mka -j$(nproc --all) bacon
      - run:
          name: Info
          no_output_timeout: 20m
          command: |
            lscpu
            df -h
      - run:
          name: Telegram Upload CI
          no_output_timeout: 20m
          command: |
            cd ~/LineageOS/out/target/product/bacon
            export ZIPNAME="lineage*.zip"
            curl -F chat_id=$CHAT_ID -F document=@$ZIPNAME -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument
workflows:
  version: 2.1
  cooking:
    jobs:
      - LineageOS-Bacon
