version: 2.1
jobs:
  Cirrus-Run:
   docker:
      - image: potyarkin/cirrus-run:latest
   steps:
      - run:
          name: Cirrus-Run
          no_output_timeout: 20m
          command: |
            cirrus-run --token 1nq0o9upajl4m2i6frfqrvu1hbj1l2hmslpq4t9 --github dopaemon/AOSP --branch main --timeout 4h .cirrus.yml
workflows:
  version: 2.1
  cooking:
    jobs:
      - Cirrus-Run
