version: 2.1
jobs:
  cm-bacon:
   docker:
      - image: dopaemon/docker-image:Ubuntu14
   steps:
      - run:
          name: Install Packages
          no_output_timeout: 20m
          command: |
            sudo add-apt-repository ppa:deadsnakes/ppa
            sudo apt update
            sudo apt upgrade -y
            sudo apt install schedtool python3.6 -y
            sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1
            sudo update-alternatives --config python
      - run:
          name: Python Version
          no_output_timeout: 20m
          command: |
            python --version
      - run:
          name: Github Config
          no_output_timeout: 20m
          command: |
            git config --global user.name "dopaemon"
            git config --global user.email "polarisdp@gmail.com"
      - run:
          name: Syncing source
          no_output_timeout: 20m
          command: |
            cd ~
            mkdir ~/cm && cd ~/cm
            repo init -u https://github.com/CyanogenMod/android.git -b cm-12.1
            repo sync -vf -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - run:
          name: Git Tree Bacon
          no_output_timeout: 20m
          command: |
            cd ~/cm
            git clone -b cm-12.1 https://github.com/CyanogenMod/android_device_oneplus_bacon.git device/oneplus/bacon
            git clone -b cm-12.1 https://github.com/CyanogenMod/android_kernel_oneplus_msm8974.git kernel/oneplus/msm8974
            git clone -b cm-12.1 https://github.com/CyanogenMod/android_device_oppo_common.git device/oppo/common
            git clone -b cm-12.1 https://github.com/CyanogenMod/android_device_qcom_common.git device/qcom/common
            git clone -b cm-12.1 https://github.com/CyanogenMod/android_device_oppo_msm8974-common.git device/oppo/msm8974-common
            git clone -b cm-12.1 https://github.com/TheMuppets/proprietary_vendor_oppo.git vendor/oppo
            git clone -b cm-12.1 https://github.com/TheMuppets/proprietary_vendor_oneplus.git vendor/oneplus
      - run:
          name: Building
          no_output_timeout: 20m
          command: |
            cd ~/cm
            source build/envsetup.sh
            export ALLOW_MISSING_DEPENDENCIES=true
            export LC_ALL=C
            lunch cm_bacon-userdebug
            mka bacon -j$(nproc --all)
      - run:
          name: Telegram Upload CI
          no_output_timeout: 20m
          command: |
            cd ~/cm/out/target/product/bacon
            export ZIPNAME="*.zip"
            curl -F chat_id=$CHAT_ID -F document=@$ZIPNAME -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument
workflows:
  version: 2.1
  cooking:
    jobs:
      - cm-bacon
