version: 2.1
jobs:
  MultiROM-Bacon:
   docker:
      - image: dopaemon/docker-image:MultiROM
   steps:
      - run:
          name: Syncing source
          no_output_timeout: 20m
          command: |
            cd ~
            mkdir ~/MultiROM && cd ~/MultiROM
            repo init -u https://github.com/KernelPanic-OpenSource/manifest.git -b mr-7.1
            repo sync -vf -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - run:
          name: Building
          no_output_timeout: 20m
          command: |
            cd ~/MultiROM
            rm -rf vendor/qcom/opensource/cryptfs_hw
            source build/envsetup.sh
            export ALLOW_MISSING_DEPENDENCIES=true
            export LC_ALL=C
            lunch tipsy_bacon-eng
            mka -j$(nproc --all) recoveryimage
      - run:
          name: Telegram Upload CI
          no_output_timeout: 20m
          command: |
            cd ~/MultiROM/out/target/product/bacon
            export ZIPNAME="MULTIROM-$(date +%d_%m_%Y_%H_%M)-bacon.zip"
            sudo zip -r9 $ZIPNAME *.img
            curl -F document=@"$ZIPNAME" https://api.telegram.org/bot$BOT_TOKEN/sendDocument?chat_id=@KernelPanic_OpenSource_CI
workflows:
  version: 2.1
  cooking:
    jobs:
      - MultiROM-Bacon
