version: 2.1
jobs:
  android:
   docker:
      - image: dopaemon/aosp:latest
   steps:
      - run:
          name: Include DPKG i386
          no_output_timeout: 20m
          command: |
            sudo dpkg --add-architecture i386
      - run:
          name: Start Building . . .
          no_output_timeout: 20m
          command: |
             mkdir aosp ; cd aosp
             git clone https://github.com/KernelPanic-OpenSource/aosp-docker.git
             cd aosp-docker
             mv * ../
             cd ..
             export AOSP_VOL=$PWD
             bash ./build-pixelexperience-pie.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - android
